server:
  #监听端口号
  port: 7777
  #用户会话session过期时间，以秒为单位
  session-timeout: 7200
  #静态资源压缩
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/javascript,image/jpeg,image/png

spring:
  #日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #数据库配置
  datasource:
    url: jdbc:mysql://14.18.43.48:3306/wisdom_www?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
    username: root
    password: KHwl20170731!@#
    driver-class-name: com.mysql.jdbc.Driver
  #AOP
  aop:
    auto: true
  #热更新
  devtools:
    restart:
      enabled: false
    additional-paths: wisdom-mng/src/main
  #JPA
  #表结构：update自动更新，none不采取措施
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #让控制器输出的json字符格式更美观
  jackson:
    serialization:
      indent-output: true
  #上传文件大小限制
  servlet:
    multipart:
      max-file-size: 5Mb
#输出日志级别
logging:
  level:
    org.springframework.web: DEBUG
#配置参数
upload:
  url: /uploads/
  file:
    path: /data/www/
    basedir: /data/tmp